### ISSUE TITLE
Type error when prescaling depthmap by a fractional value.

### ISSUE THREAD

**Issue by Seedmanc** [graemeniedermayer/stable-diffusion-webui-normalmap-script#5]
> img_output *= scale_depth
> numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('uint16') with casting rule 'same_kind' 

Scaling by 2 or 3 works, but currently there's no way to halve the depth.

**Comment by graemeniedermayer** [comment]
Thank you! Updated it so it casts correctly.
