### ISSUE TITLE
Question about lighting

### ISSUE THREAD

**Issue by pion-changho** [graemeniedermayer/stable-diffusion-webui-normalmap-script#7]
Thank you for great script for Automatic 1111.
I have some question about lighting, as you attached in the REAME.md.
How can I change the lights with normal map?

**Comment by graemeniedermayer** [comment]
Thanks! I made a youtube video about it a while ago that didn't link to https://youtu.be/8uvTzg9I8Yg?t=130 .

To summarize, the simplest method is to use an external tool like blender and import the normal maps onto a plane with the original image. Hope this helps!

**Comment by pion-changho** [comment]
@graemeniedermayer Thank you very much!
